# Generated by Django 4.1.2 on 2024-10-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
