# Generated by Django 4.1.2 on 2024-10-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='points_allotted',
            field=models.IntegerField(default=0),
        ),
    ]
